### PR TITLE
runtime 9151 update

### PR DESCRIPTION
**Pull request by hitchhooker**
bumping deps and runtime update with
``` 
npx npm-check-updates -u 
```

### CODE REVIEW

**Review by Tbaut — COMMENTED** [review]
Thanks for that, did you let the app run to test those upgrades? 
Also did you forget to upgrade the metadata and spec version you mention in the title? That's in `metadata.json`, and I usually get them with 
```
console.log(api.runtimeMetadata.asCallsOnly.toHex());
console.log(api.runtimeVersion.specVersion)
```

In pjs apps, connected to the network you are interested to upgrade. https://polkadot.js.org/apps/#/js

**Comment by Tbaut** [comment]
This looks good thanks a lot. I'll add Astar, Interlay and Zeitgeist and then cut a release

**Review by Tbaut — APPROVED** [review]

**Comment by Tbaut** [comment]
Linting isn't happy, I'll fix that in another PR.

**Comment by hitchhooker** [comment]
Awesome. I end up having a struggle with android studio not loading correctly on bspwm, so couldnt ever get it built.

**Pull request closed without merging**
